---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3.10
  tasks:
    - name: Pull image
      docker_image:
        name: naitik1/calculator:latest
        source: pull
    - name: Start docker service
      when: ansible_facts['os_family'] == "Debian"
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it --name Calculator naitik1/calculator